/**
 * Curated common tags for Photo Library hybrid tagging.
 * Lowercase for consistency; display can title-case if desired.
 */

export const COMMON_TAGS: string[] = [
  "coastal",
  "transitional",
  "modern",
  "traditional",
  "farmhouse",
  "contemporary",
  "white kitchen",
  "white oak",
  "natural wood",
  "painted cabinets",
  "two-tone cabinets",
  "marble",
  "quartz",
  "granite",
  "subway tile",
  "herringbone",
  "statement lighting",
  "pendants",
  "under cabinet lighting",
  "open concept",
  "built-ins",
  "floating shelves",
  "brass hardware",
  "black hardware",
  "shiplap",
  "beams",
  "vaulted ceiling",
  "wainscoting",
  "fireplace",
  "waterfall island",
  "island seating",
  "walk-in shower",
  "freestanding tub",
  "double vanity",
  "glass shower",
  "tile surround",
  "hardwood floors",
  "lvp",
  "mudroom",
  "pantry upgrade",
  "laundry upgrade",
  "outdoor living",
  "screen porch",
  "deck rebuild",
  "pool refresh",
  "frog",
  "addition",
  "stairs",
];
