-- Phase 7A: Structured measurement fields on Room (already applied to DB)
ALTER TABLE "Room" ADD COLUMN "wallsSF" DOUBLE PRECISION;
ALTER TABLE "Room" ADD COLUMN "ceilingSF" DOUBLE PRECISION;
ALTER TABLE "Room" ADD COLUMN "perimeterLF" DOUBLE PRECISION;
ALTER TABLE "Room" ADD COLUMN "paintableSF" DOUBLE PRECISION;
ALTER TABLE "Room" ADD COLUMN "windowCount" INTEGER;
ALTER TABLE "Room" ADD COLUMN "windowsSF" DOUBLE PRECISION;
ALTER TABLE "Room" ADD COLUMN "doorCount" INTEGER;
ALTER TABLE "Room" ADD COLUMN "doorsSF" DOUBLE PRECISION;
ALTER TABLE "Room" ADD COLUMN "measurementSource" TEXT;
ALTER TABLE "Room" ADD COLUMN "rendrRoomMappings" JSONB;
ALTER TABLE "Room" ADD COLUMN "roomDetail" JSONB;
